<a href="https://colab.research.google.com/github/shanmcm/Sentiment-Analysis-Amazon-Musical-Instruments-Reviews/blob/main/Amazon_Reviews.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
import os
import random
import pandas as pd
from torchtext.legacy import data
#import torchtext
import pickle5 as pickle

from torch.utils.data import DataLoader
from sklearn.model_selection import GridSearchCV, train_test_split

import params
import net

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Error loading corpus: Package 'corpus' not found in index
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package sentiwordnet to /root/nltk_data...
[nltk_data]   Package sentiwordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


In [2]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [3]:
!pip install transformers
from dataset import AmazonDataset

dataset = AmazonDataset()
dataset.load_dataset()
dataset.data
# from google.colab import drive
# drive.mount('/content/drive/')
# DATA_PATH = "/content/drive/MyDrive/NLP_Progetto"
# infile = open(DATA_PATH+'/amazonDataset.pkl','rb')
# best_model2 = pickle.load(infile)

True
weee
ciao


0        much write exactly supposed filters pop sounds...
1        product exactly quite affordablei realized dou...
2        primary job device block breath would otherwis...
3        nice windscreen protects mxl mic prevents pops...
4        pop filter great looks performs like studio fi...
                               ...                        
10256                                 great expected thank
10257    ive thinking trying nanoweb strings bit put hi...
10258    tried coated strings past including elixirs ne...
10259    well made elixir developed taylor guitars stri...
10260    strings really quite good wouldnt call perfect...
Name: reviewText, Length: 10254, dtype: object

In [4]:
print(dataset.data)

0        much write exactly supposed filters pop sounds...
1        product exactly quite affordablei realized dou...
2        primary job device block breath would otherwis...
3        nice windscreen protects mxl mic prevents pops...
4        pop filter great looks performs like studio fi...
                               ...                        
10256                                 great expected thank
10257    ive thinking trying nanoweb strings bit put hi...
10258    tried coated strings past including elixirs ne...
10259    well made elixir developed taylor guitars stri...
10260    strings really quite good wouldnt call perfect...
Name: reviewText, Length: 10254, dtype: object


In [5]:
dataset.__getitem__(4)

NN
NN
JJ
NNS
NNS
IN
NN
NN
PRP$
NN
VBG
NNS
NN
NNS
VBZ
VBN
VBG


[tensor([0., 0., 0.,  ..., -0., -0., -0.]),
 tensor([0., 0., 0.,  ..., -0., -0., -0.]),
 tensor([0., 0., 0.,  ..., 0., -0., 0.]),
 tensor([0., 0., 0.,  ..., 0., -0., 0.]),
 tensor([-0., -0., 0.,  ..., -0., 0., -0.]),
 tensor([ 0.0350,  0.0094,  0.0722,  ..., -0.0513, -0.0029, -0.0458]),
 tensor([0., 0., 0.,  ..., -0., 0., -0.]),
 tensor([0., 0., 0.,  ..., -0., -0., -0.]),
 tensor([-0.7142,  0.4665,  1.1581,  ..., -0.9884,  0.5268, -1.0483]),
 tensor([-0.3330,  0.5854,  0.7720,  ..., -0.7944,  0.6782, -0.2575]),
 tensor([0., 0., 0.,  ..., 0., -0., -0.]),
 tensor([-0., 0., 0.,  ..., -0., 0., -0.]),
 tensor([-0., 0., 0.,  ..., -0., -0., -0.]),
 tensor([0., 0., 0.,  ..., -0., -0., 0.]),
 tensor([-0., -0., 0.,  ..., -0., 0., -0.]),
 tensor([-0., 0., 0.,  ..., -0., -0., -0.]),
 tensor([-0., -0., 0.,  ..., -0., -0., 0.])]

In [6]:
x_train, x_test, y_train, y_test = train_test_split(dataset.data, dataset.labels, train_size=0.7, random_state=0)

#train_data, valid_data = train_data.split(split_ratio=dev_size, random_state=random.seed(seed))
train_data = { 'Features': x_train, 'Labels': y_train}
test_data = {'Features': x_test, 'Labels': y_test}

train_data = pd.DataFrame(train_data)
test_data = pd.DataFrame(test_data)

#  BucketIterator : Defines an iterator that batches examples of similar lengths together to minimize the amount of padding needed.
# by setting sort_within_batch = True.
train_iterator, test_iterator = data.BucketIterator.splits((train_data, test_data),
    batch_size = params.BATCH_SIZE,
    sort_key = lambda x: len(x.text), # Sort the batches by text length size
    sort_within_batch = True,
    device = device)

In [7]:
to_train = True
#pad_index = Text.vocab.stoi[Text.pad_token]
batch_size = params.BATCH_SIZE
hidden_dim = 128
embedding_size = len(dataset.__getitem__(0)[0]) #lunghezza embedding (selezionato uno a caso perchè tanto tutti hanno la stessa dimensione)
dropout_rate = params.DROPOUT_RATE
# Build the model
lstm_model = net.SentimentAnalysis(batch_size,
                                   hidden_dim,
                                   embedding_size,
                                   dropout_rate) #modificato LSTM con SentimentAnalysis (nome rete)


JJ
NN
RB
VBN
NNS
NN
NNS
NNS
JJ
NN
CD
JJS
NNS
NN
NNS
NN
MD
RB
VB
RB
NN
IN
NN


In [8]:
lr = params.LR
epochs = params.NUM_EPOCHS

# optimization algorithm
optimizer = torch.optim.Adam(lstm_model.parameters(), lr=lr)


# train and validate
if (to_train):

    for epoch in range(epochs):

        # training 
        epoch_loss = 0
        epoch_acc = 0
        for batch in train_iterator:
            optimizer.zero_grad()
            # retrieve text and no. of words
            text, text_lengths = batch.text

            predictions = lstm_model(text, text_lengths) # batch_size, hidden_dim, vocab_size, window, dropout_rate
            loss = 0.5*nn.CrossEntropyLoss(predictions, batch.labels.squeeze())+ 0.5*nn.MSELoss(predictions, batch.labels.squeeze())

            winners = predictions.argmax(dim=1)
            corrects = (winners == batch.labels)
            accuracy = corrects.sum().float() / float(batch.labels.size(0))

            # perform backpropagation
            loss.backward()

            optimizer.step()

            epoch_loss += loss.item()
            epoch_acc += accuracy.item()
            
        train_loss, train_acc = epoch_loss / len(train_iterator), epoch_acc / len(train_iterator)
        
        # validation
        epoch_loss = 0
        epoch_acc = 0

        lstm_model.eval()

        with torch.no_grad():
            for batch in valid_iterator:
                text, text_lengths = batch.text

                predictions = lstm_model(text, text_lengths).squeeze(1)

                loss = 0.5*nn.CrossEntropyLoss(predictions, batch.labels)+ 0.5*nn.MSELoss(predictions, batch.labels)

                winners = predictions.argmax(dim=1)
                corrects = (winners == batch.labels)
                accuracy = corrects.sum().float() / float(batch.labels.size(0))

                epoch_loss += loss.item()
                epoch_acc += accuracy.item()

        valid_loss, valid_acc =  epoch_loss / len(valid_iterator), epoch_acc / len(valid_iterator)


        # save best model
        if valid_loss < best_valid_loss:
            best_valid_loss = valid_loss
            torch.save(lstm_model.state_dict(), 'saved_weights_BiLSTM.pt')

        print(f'\tTrain Loss: {train_loss:.3f} | Train Acc: {train_acc * 100:.2f}%')
        print(f'\t Val. Loss: {valid_loss:.3f} |  Val. Acc: {valid_acc * 100:.2f}%')


# load weights and make predictions
lstm_model.load_state_dict(torch.load("saved_weights_BiLSTM.pt"))
epoch_loss = 0
epoch_acc = 0

lstm_model.eval()

with torch.no_grad():
    for batch in test_iterator:
        text, text_lengths = batch.text

        predictions = lstm_model(text, text_lengths).squeeze(1)

        loss = 0.5*nn.CrossEntropyLoss(predictions, batch.labels)+ 0.5*nn.MSELoss(predictions, batch.labels)

        winners = predictions.argmax(dim=1)
        corrects = (winners == batch.labels)
        accuracy = corrects.sum().float() / float(batch.labels.size(0))

        epoch_loss += loss.item()
        epoch_acc += accuracy.item()

test_loss, test_acc =  epoch_loss / len(test_iterator), epoch_acc / len(test_iterator)
print(f'Test Loss: {test_loss:.3f} | Test Acc: {test_acc * 100:.2f}%')

KeyError: ignored

In [ ]:
with open('amazonDataset.pkl', 'rb') as fid:
  data3 = pickle.load(fid)

In [ ]:
data_string = pickle.dumps(data_org)
print('PICKLE:', data_string )

In [ ]:
with open('amazonDataset.pkl', 'rb') as fid:
  data3 = pickle.load(fid)

In [ ]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

Parte Lucia

In [ ]:
'''
Qui c'è un bozza sulla parte iniziale (settaggio parametri, creazione train test ecc)
Faccio riferimento a una funzione cleanup_text che va riempita in base al preprocessing
'''
import params
from lstm_cell import LSTMCell

def cleanup_text(texts):
  cleaned_text = []
  for text in texts:
      # remove punctuation, ecc....
      text = re.sub('[!#?,.:";]', ' ', text)
     
      cleaned_text.append(text)
  return cleaned_text


char_based = True
if char_based:
    tokenizer = lambda s: list(s) # char-based
else:
    tokenizer = lambda s: s.split() # word-based


# hyper-parameters:
lr = params.LR
batch_size = params.BATCH_SIZE
dropout_rate = params.DROPOUT_RATE
#dropout_keep_prob = 0.5
embedding_size = 300
max_document_length = 100  # each sentence has until 100 words
dev_size = 0.8 # split percentage to train\validation data
max_size = 5000 # maximum vocabulary size
seed = params.SEED
num_classes = params.NUM_CLASSES # output dimension of LSTM
num_hidden_nodes = 93
hidden_dim2 = 128
num_layers = 2  # LSTM layers
bi_directional = True
epochs = params.NUM_EPOCHS

Text = data.Field(preprocessing=cleanup_text, tokenize=tokenizer, batch_first=True, include_lengths=True, fix_length=max_document_length) # fix_length - make the sentences padded in the same lengths for all the batches
Label = data.Field(sequential=False, use_vocab=False, pad_token=None, unk_token=None)

# All files:
fields = [('text', Text), ('labels', Label)]

data_type = "token" # or: "morph"

train_data, test_data = data.TabularDataset.splits(
 # https://pytorch.org/text/_modules/torchtext/data/dataset.html
)

train_data, valid_data = train_data.split(split_ratio=dev_size, random_state=random.seed(seed))

# Build_vocab : It will first create a dictionary mapping all the unique words present in the train_data to an
# index and then after it will use word embedding (random, Glove etc.) to map the index to the corresponding word embedding.
Text.build_vocab(train_data, max_size=max_size)
Label.build_vocab(train_data)
vocab_size = len(Text.vocab)

#  BucketIterator : Defines an iterator that batches examples of similar lengths together to minimize the amount of padding needed.
# by setting sort_within_batch = True.
train_iterator, valid_iterator, test_iterator = data.BucketIterator.splits((train_data, valid_data, test_data),
    batch_size = batch_size,
    sort_key = lambda x: len(x.text), # Sort the batches by text length size
    sort_within_batch = True,
    device = device)

Parte Shannon

In [ ]:
to_train = True
pad_index = Text.vocab.stoi[Text.pad_token]

# Build the model
lstm_model = SentimentAnalysis(vocab_size, embedding_size, num_hidden_nodes, hidden_dim2 , num_classes, num_layers,
                bi_directional, dropout_keep_prob, pad_index) #modificato LSTM con SentimentAnalysis (nome rete)

# optimization algorithm
optimizer = torch.optim.Adam(lstm_model.parameters(), lr=lr)

# train and validate
if (to_train):

    for epoch in range(epochs):

        # training 
        epoch_loss = 0
        epoch_acc = 0
        for batch in train_iterator:
            optimizer.zero_grad()
            # retrieve text and no. of words
            text, text_lengths = batch.text

            predictions = lstm_model(text, text_lengths) # batch_size, hidden_dim, vocab_size, window, dropout_rate
            loss = 0.5*nn.CrossEntropyLoss(predictions, batch.labels.squeeze())+ 0.5*nn.MSELoss(predictions, batch.labels.squeeze())

            winners = predictions.argmax(dim=1)
            corrects = (winners == batch.labels)
            accuracy = corrects.sum().float() / float(batch.labels.size(0))

            # perform backpropagation
            loss.backward()

            optimizer.step()

            epoch_loss += loss.item()
            epoch_acc += accuracy.item()
            
        train_loss, train_acc = epoch_loss / len(train_iterator), epoch_acc / len(train_iterator)
        
        # validation
        epoch_loss = 0
        epoch_acc = 0

        lstm_model.eval()

        with torch.no_grad():
            for batch in valid_iterator:
                text, text_lengths = batch.text

                predictions = lstm_model(text, text_lengths).squeeze(1)

                loss = 0.5*nn.CrossEntropyLoss(predictions, batch.labels)+ 0.5*nn.MSELoss(predictions, batch.labels)

                winners = predictions.argmax(dim=1)
                corrects = (winners == batch.labels)
                accuracy = corrects.sum().float() / float(batch.labels.size(0))

                epoch_loss += loss.item()
                epoch_acc += accuracy.item()

        valid_loss, valid_acc =  epoch_loss / len(valid_iterator), epoch_acc / len(valid_iterator)


        # save best model
        if valid_loss < best_valid_loss:
            best_valid_loss = valid_loss
            torch.save(lstm_model.state_dict(), 'saved_weights_BiLSTM.pt')

        print(f'\tTrain Loss: {train_loss:.3f} | Train Acc: {train_acc * 100:.2f}%')
        print(f'\t Val. Loss: {valid_loss:.3f} |  Val. Acc: {valid_acc * 100:.2f}%')


# load weights and make predictions
lstm_model.load_state_dict(torch.load("saved_weights_BiLSTM.pt"))
epoch_loss = 0
epoch_acc = 0

lstm_model.eval()

with torch.no_grad():
    for batch in test_iterator:
        text, text_lengths = batch.text

        predictions = lstm_model(text, text_lengths).squeeze(1)

        loss = 0.5*nn.CrossEntropyLoss(predictions, batch.labels)+ 0.5*nn.MSELoss(predictions, batch.labels)

        winners = predictions.argmax(dim=1)
        corrects = (winners == batch.labels)
        accuracy = corrects.sum().float() / float(batch.labels.size(0))

        epoch_loss += loss.item()
        epoch_acc += accuracy.item()

test_loss, test_acc =  epoch_loss / len(test_iterator), epoch_acc / len(test_iterator)
print(f'Test Loss: {test_loss:.3f} | Test Acc: {test_acc * 100:.2f}%')

In [ ]:
!git status

In [ ]:
!git add --all

In [ ]:
!git config --global user.email "s289958@studenti.polito.it" # mettere email del proprio github account

In [ ]:
!git commit -m"Added utils.py with useful functions"

In [ ]:
!git push